### PR TITLE
Update hardhat/ethers/waffle

### PR DESCRIPTION
**Pull request by fedgiac**
Updates remaining outdated packages that are tightly coupled together and need to be updated in parallel.

Note that Ethers has been updated to the latest minor version for v5, an upgrade to v6 requires many changes and will trigger a new major release of this project.

Also note that I only updated Tenderly to v1.1 and froze it at that minor version. Using the latest version would require a few code changes, importing an extra package, increase the number of network request on _any_ invocation of `hardhat` and would annoyingly increase the amount of logs that are printed every time `hardhat` is called (the extra logs might be reduced but not configured away as the logging level is hardcoded in the plugin). Issue #32 is related.

The changes to the proxy code appear to be caused by a change in behavior in `hardhat-deploy`, the new code should have the same effect (this is confirmed by our tests). I found a related issue [here](https://github.com/wighawag/hardhat-deploy/issues/294) and the new behavior appears to be intended behavior.

### Test Plan

Test a few commands and verify that everything works as usual, notably `yarn deploy` and `yarn bench:trace`.

### CODE REVIEW

**Comment by fedgiac** [comment]
The chain of dependencies for `classic-level` is `classic-level` → `level` → `@nomicfoundation/ethereumjs-blockchain`.
The latter is [based on](https://www.npmjs.com/package/@nomicfoundation/ethereumjs-blockchain) `@ethereumjs/blockchain`, which last updated `level` [10 months ago](https://github.com/ethereumjs/ethereumjs-monorepo/blame/e8cf85bb8207a273d0ecdb0bf132d22b9b5304bc/packages/blockchain/package.json#L51), so at least it isn't a new dependency. The amount of "native code" is too much for me to evaluate, so I trust that nomicfoundation/hardhat did their job properly and will merge this PR once approved.

**Review by bh2smith — APPROVED** [review]
Looks fine to me, but CI isn't passing.

**Comment by bh2smith** [comment]
Life would be so much better (I think) if ethers were updated here! I am having issues with things like this:

https://github.com/cowprotocol/solver-rewards/actions/runs/4832848554/jobs/8612129079

**Comment by fedgiac** [comment]
Sorry about this, it's most likely a problem because of ethers being a peer dependency, more than the version of the dependency itself, you can see other people mentioning this issue [here](https://github.com/cowprotocol/contracts/pull/44). Unfortunately, until we update the whole repo to support ethers v6 (or switch to ethers as standard dependency) this will be an issue. It's surprisingly tricky to update because Hardhat doesn't support ethers v6 already and there is no easy way to override subdependencies when they are peer dependencies.

**Pull request merged**
