### PR TITLE
Update GPv2Settlement.sol

### PR DESCRIPTION
**Pull request by Aryan9592**
Enhanced the 'for' loop by changing `uint256 i = 0` to `uint256 i;` which was already been done in 1 of the three loops, and changed `i++` to `++i` which proves to be a bit efficient...Refer [this](https://gist.github.com/grGred/9bab8b9bad0cd42fc23d4e31e7347144#for-loops-improvement)

Also got some typos or grammatical errors fixed!

Thanks @fleupold

### CODE REVIEW

**Comment by Aryan9592** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by fedgiac — APPROVED** [review]
Thanks for your contribution!

I ran our benchmarks against these changes and I don't see any gas improvement. A possible reason is that we use Solidity 0.7 and the linked reference is for 0.8.
Anyway, I don't mind merging as is since it's more consistent and we'll most likely switch this code to 0.8 when working on the future updated contracts. 



<details><summary>Comparison</summary>

```
$ yarn bench:compare main
yarn run v1.22.19
$ bash bench/compare.sh main
Running benchmark for patch-1...
Running benchmark for main...
Warning: unable to recover token list from 1inch
Warning: unable to recover token list from 1inch
=== Settlement Gas Benchmarks ===
--------------+--------------+--------------+--------------+--------------
       tokens |       trades | interactions |      refunds |          gas 
--------------+--------------+--------------+--------------+--------------
            2 |           10 |            0 |            0 |       710058  (change: -3 / trade)
            3 |           10 |            0 |            0 |       719926  (change: 3 / trade)
            4 |           10 |            0 |            0 |       729758  (change: -1 / trade)
            5 |           10 |            0 |            0 |       739590  (change: -1 / trade)
            6 |           10 |            0 |            0 |       749410  (change: -2 / trade)
            7 |           10 |            0 |            0 |       759230  (change: 1 / trade)
            8 |           10 |            0 |            0 |       768978  (change: -4 / trade)
            8 |           20 |            0 |            0 |      1392807  (change: 1 / trade)
            8 |           30 |            0 |            0 |      1992033  (change: -1 / trade)
            8 |           40 |            0 |            0 |      2592097  (change: 1 / trade)
            8 |           50 |            0 |            0 |      3191719  (change: 1 / trade)
            8 |           60 |            0 |            0 |      3792213  (change: 0 / trade)
            8 |           70 |            0 |            0 |      4392742  (change: 0 / trade)
            8 |           80 |            0 |            0 |      4993495  (change: 0 / trade)
            2 |           10 |            1 |            0 |       771234  (change: 2 / trade)
            2 |           10 |            2 |            0 |       798998  (change: 0 / trade)
            2 |           10 |            3 |            0 |       826714  (change: 2 / trade)
            2 |           10 |            4 |            0 |       854382  (change: -6 / trade)
            2 |           10 |            5 |            0 |       882194  (change: 2 / trade)
            2 |           10 |            6 |            0 |       909874  (change: -1 / trade)
            2 |           10 |            7 |            0 |       937602  (change: -2 / trade)
            2 |           10 |            8 |            0 |       965330  (change: -2 / trade)
            2 |           50 |            0 |           10 |      2899247  (change: -2 / trade)
            2 |           50 |            0 |           15 |      2909581  (change: 0 / trade)
            2 |           50 |            0 |           20 |      2919868  (change: 0 / trade)
            2 |           50 |            0 |           25 |      2930108  (change: 1 / trade)
            2 |           50 |            0 |           30 |      2940313  (change: -1 / trade)
            2 |           50 |            0 |           35 |      2950506  (change: -1 / trade)
            2 |           50 |            0 |           40 |      2960833  (change: 2 / trade)
            2 |           50 |            0 |           45 |      2971137  (change: 1 / trade)
            2 |           50 |            0 |           50 |      2981286  (change: 0 / trade)
            2 |            2 |            0 |            0 |       192316  (change: 0 / trade)
            2 |            1 |            1 |            0 |       188719  (change: 0 / trade)
           10 |           80 |           10 |           20 |      4966807  (change: 1 / trade)
Done in 250.49s.
```
</details>

**Comment by Aryan9592** [comment]
yeah @fedgiac, Even I feel that the reason is probably that solidity version.
Still Thanks!

**Review by mfw78 — APPROVED** [review]
@Aryan9592 Thanks for the taking the time to read the contract carefully!

**Pull request merged**
